---
- name: Create {{ roon_bridge_path }}
  ansible.builtin.file:
    path: "{{ roon_bridge_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0775
  become: true

- name: Create {{ roon_bridge_path }}/data
  ansible.builtin.file:
    path: "{{ roon_bridge_path }}/data"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0775
  become: true
