---
- name: apt update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr
  become: true

- name: Configure audio system
  ansible.builtin.import_tasks: audio.yml

- name: Start Roon Bridge
  ansible.builtin.import_tasks: roon-bridge-docker.yml
